version: '3.9'

services:
  mysql:
    image: phanhung28/mysql-v1:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  adminer:
    image: adminer
    container_name: my_adminer_container
    ports:
      - "8888:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
